export const GET_PAISES = "GET_PAISES";
export const PAIS_DETALLE = "PAIS_DETALLE";
export const FILTER_CONTINENTE = "FILTER_CONTINENTE";
export const ORDER_NOMBRE = "ORDER_NOMBRE";
export const ORDER_POBLACION = "ORDER_POBLACION";
export const ORDER_DESAC = "ORDER_DESAC";
export const FILTER_SEARCH = "FILTER_SEARCH";
export const SELECT_PAIS = "SELECT_PAIS";
export const FILTER_ACTIVIDAD = "FILTER_ACTIVIDAD";
export const GET_ACTIVIDADES = "GET_ACTIVIDADES";


