export const GET_PAISES = "GET_PAISES";
export const PAIS_DETALLE = "PAIS_DETALLE";
export const FILTER_CONTINENTE = "FILTER_CONTINENTE";
export const ORDER_NOMBRE = "ORDER_NOMBRE";
export const ORDER_POBLACION = "ORDER_POBLACION";
export const FILTER_CONTINENTE_ORDEN_NAME = "FILTER_CONTINENTE_ORDEN_NAME";
export const FILTER_CONTINENTE_ORDEN_POB = "FILTER_CONTINENTE_ORDEN_POB";
export const FILTER_NAME = "FILTER_NAME";

